ignore:
  - 'app/controllers/concerns/loads_and_authorizes_resource.rb':
    - Security/Eval # TODO we should have this audited.
    - Style/EvalWithLocation # TODO we should have this audited.
  - '**/*':
    - Style/TrailingCommaInArguments
    - Style/TrailingCommaInArrayLiteral
    - Style/TrailingCommaInHashLiteral
    - Style/CommentedKeyword
  - 'app/controllers/**/*':
    - Style/RedundantAssignment
  - 'config/routes.rb':
    - Lint/UselessAssignment
