version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2

jobs:
  build:
    docker:
      - image: circleci/ruby:2.7.4-node-browsers
        environment:
          PGHOST: localhost
          PGUSER: bullet_train
          RAILS_ENV: test
      - image: circleci/postgres
        environment:
          POSTGRES_HOST_AUTH_METHOD: trust
          POSTGRES_DB: bullet_train_test
          POSTGRES_USER: bullet_train
    executor: ruby/default
    steps:
      - checkout
      - run: gem update --system
      - run: gem install bundler:2.2.0
      - run:
          name: Which bundler?
          command: bundle -v
      - ruby/bundle-install
      - run:
          name: Install packages
          command: yarn install

      # We run this because the DB might not be available
      # for a while due to a race condition
      - run: dockerize -wait tcp://localhost:5432 -timeout 1m

      - run:
          name: Run Bullet Train test suite
          command: bundle exec rails test && bundle exec rails test:system
